/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pairSol from "./Pair.sol";
export type { pairSol };
import type * as routerSol from "./Router.sol";
export type { routerSol };
export type { Factory } from "./Factory";
export type { TestToken } from "./TestToken";
